import { NextRequest, NextResponse } from 'next/server'
import { BigQuery } from '@google-cloud/bigquery'
import { serverCache, CACHE_KEYS, CACHE_TTL } from '@/lib/cache'
import { getBigQueryConfig } from '@/lib/bigquery'

const bigquery = new BigQuery(
  getBigQueryConfig(
    process.env.GOOGLE_CLOUD_PROJECT_ID || '',
    'GOOGLE_CLOUD_KEY_FILE'
  )
)

const PLAYER_GAMELOGS_TTL = 24 * 60 // 24 hours in minutes

async function fetchPlayerGamelogsFromBigQuery(playerId: string) {
  console.log(`Fetching gamelogs for player ${playerId} from BigQuery...`)
  const query = `
    SELECT 
      season,
      season_type,
      week,
      game_id,
      home_team,
      away_team,
      venue,
      gsis_id,
      player_name,
      team,
      opponent,
      \`2025_Team\` as team_2025,
      position,
      espn_id,
      cbs_id,
      espn_headshot,
      pbp_player_name,
      pfr_id,
      Off_snaps,
      Off_snap_pct,
      pos_rank,
      depth_label_by_snaps,
      starter_flag,
      attempts,
      completions,
      pass_comp_pct,
      passing_yards,
      pass_ypa,
      passing_tds,
      interceptions,
      sacks,
      sack_yards,
      passing_air_yards,
      passing_yac,
      passing_first_downs,
      targets,
      receptions,
      receiving_yards,
      receiving_tds,
      receiving_air_yards,
      receiving_yac,
      receiving_first_downs,
      carries,
      rushing_yards,
      rushing_tds,
      rushing_first_downs,
      td_rush,
      td_rec,
      td_total,
      longest_pass,
      longest_rec,
      longest_rush,
      passer_dropbacks,
      passer_attempts,
      passer_completions,
      passer_sacks_taken,
      passer_scrambles,
      passer_pass_yards,
      passer_interceptions,
      passer_pass_tds,
      passer_short_att,
      passer_intermediate_att,
      passer_deep_att,
      passer_left_att,
      passer_middle_att,
      passer_right_att,
      passer_short_left_att,
      passer_short_middle_att,
      passer_short_right_att,
      passer_deep_left_att,
      passer_deep_middle_att,
      passer_deep_right_att,
      passer_rz20_att,
      passer_rz20_comp,
      passer_rz20_tds,
      passer_rz10_att,
      passer_rz10_comp,
      passer_rz10_tds,
      passer_gl5_att,
      passer_gl5_tds,
      passer_xpass_avg,
      passer_pass_oe_avg,
      passer_qb_epa_avg,
      passer_epa_total,
      passer_epa_per_dropback,
      passer_adot,
      passer_avg_td_prob_on_attempt,
      passer_avg_wp_on_attempt,
      passer_avg_vegas_wp_on_attempt,
      passer_pressured_att,
      passer_pressured_comp_pct,
      passer_pressured_ypa,
      passer_clean_att,
      passer_clean_comp_pct,
      passer_clean_ypa,
      passer_third_down_att,
      passer_two_min_att,
      team_plays,
      team_dropbacks,
      team_pass_att,
      team_air_yards,
      team_rz20_dropbacks,
      team_rz20_pass_att,
      team_rz10_dropbacks,
      team_rz10_pass_att,
      team_short_att,
      team_intermediate_att,
      team_deep_att,
      team_left_att,
      team_middle_att,
      team_right_att,
      team_third_down_att,
      team_two_min_att,
      team_targets,
      team_rz20_targets,
      team_rz10_targets,
      team_gl5_targets,
      team_short_targets,
      team_intermediate_targets,
      team_deep_targets,
      team_left_targets,
      team_middle_targets,
      team_right_targets,
      receiver_targets,
      receiver_receptions,
      receiver_receiving_yards,
      receiver_receiving_tds,
      receiver_yards_per_reception,
      receiver_yards_per_target,
      receiver_catch_rate,
      receiver_air_yards,
      receiver_yac,
      receiver_yac_per_reception,
      receiver_racr,
      receiver_adot,
      receiver_epa_total_on_target,
      receiver_epa_per_target,
      receiver_air_epa_total,
      receiver_yac_epa_total,
      receiver_comp_air_epa_total,
      receiver_comp_yac_epa_total,
      receiver_wpa_total_on_target,
      receiver_wpa_per_target,
      receiver_avg_td_prob_on_target,
      receiver_avg_td_prob_on_reception,
      receiver_avg_wp_on_target,
      receiver_avg_wp_on_reception,
      receiver_avg_vegas_wp_on_target,
      receiver_short_targets,
      receiver_intermediate_targets,
      receiver_deep_targets,
      receiver_left_targets,
      receiver_middle_targets,
      receiver_right_targets,
      receiver_rz20_targets,
      receiver_rz20_receptions,
      receiver_rz20_tds,
      receiver_rz10_targets,
      receiver_rz10_receptions,
      receiver_rz10_tds,
      receiver_gl5_targets,
      receiver_gl5_tds,
      receiver_first_down_receptions,
      receiver_third_down_targets,
      receiver_fourth_down_targets,
      receiver_two_min_targets,
      receiver_explosive20_plus_recs,
      receiver_target_share,
      receiver_air_yards_share,
      receiver_rz20_target_share,
      receiver_rz10_target_share,
      receiver_gl5_target_share,
      receiver_short_target_share,
      receiver_intermediate_target_share,
      receiver_deep_target_share,
      receiver_left_target_share,
      receiver_middle_target_share,
      receiver_right_target_share,
      rusher_carries,
      rusher_rush_yards,
      rusher_yards_per_carry,
      rusher_rush_tds,
      rusher_first_downs,
      rusher_successes,
      rusher_success_rate,
      rusher_epa_total,
      rusher_epa_per_carry,
      rusher_wpa_total,
      rusher_wpa_per_carry,
      rusher_designed_carries,
      rusher_scramble_carries,
      rusher_left_loc_carries,
      rusher_middle_loc_carries,
      rusher_right_loc_carries,
      rusher_end_gap_carries,
      rusher_tackle_gap_carries,
      rusher_guard_gap_carries,
      rusher_middle_gap_carries,
      rusher_left_edge_carries,
      rusher_right_edge_carries,
      rusher_interior_carries,
      rusher_rz20_carries,
      rusher_rz20_tds,
      rusher_rz10_carries,
      rusher_rz10_tds,
      rusher_gl5_carries,
      rusher_gl5_tds,
      rusher_gl3_carries,
      rusher_gl1_carries,
      rusher_stuffed_carries,
      rusher_yds_1_3_carries,
      rusher_yds_4_7_carries,
      rusher_yds_8_plus_carries,
      rusher_explosive10_plus,
      rusher_explosive15_plus,
      rusher_explosive20_plus,
      rusher_short_yd_carries,
      rusher_short_yd_conversions,
      rusher_avg_td_prob_on_carry,
      rusher_avg_wp_on_carry,
      rusher_avg_vegas_wp_on_carry,
      team_rush_att,
      team_designed_rush_att,
      team_scramble_rush_att,
      team_rz20_rush_att,
      team_rz10_rush_att,
      team_gl5_rush_att,
      team_gl3_rush_att,
      team_gl1_rush_att,
      team_left_loc_rush_att,
      team_middle_loc_rush_att,
      team_right_loc_rush_att,
      team_end_gap_rush_att,
      team_tackle_gap_rush_att,
      team_guard_gap_rush_att,
      team_middle_gap_rush_att,
      team_left_edge_rush_att,
      team_right_edge_rush_att,
      team_middle_interior_rush_att,
      rusher_carry_share,
      rusher_designed_carry_share,
      rusher_scramble_carry_share,
      rusher_rz20_carry_share,
      rusher_rz10_carry_share,
      rusher_gl5_carry_share,
      rusher_gl3_carry_share,
      rusher_gl1_carry_share,
      rusher_left_loc_carry_share,
      rusher_middle_loc_carry_share,
      rusher_right_loc_carry_share,
      rusher_end_gap_carry_share,
      rusher_tackle_gap_carry_share,
      rusher_guard_gap_carry_share,
      rusher_middle_gap_carry_share,
      rusher_left_edge_carry_share,
      rusher_right_edge_carry_share,
      rusher_interior_carry_share,
      player_display_name
    FROM \`nfl25-469415.v2_nfl_silver.Player_Gamelogs_v3\`
        WHERE espn_id = CAST(@playerId AS INT64)
      AND season_type = 'REG'
    ORDER BY season DESC, week DESC
  `
  
  const options = {
    query,
    params: { playerId }
  }
  
  const [rows] = await bigquery.query(options)
  console.log(`Fetched ${rows.length} gamelog entries for player ${playerId}`)
  return rows
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id: playerId } = await params
    const cacheKey = `player_gamelogs_${playerId}`
    
    // Check cache first
    let gamelogs = serverCache.get(cacheKey)
    
    if (!gamelogs) {
      // Fetch from BigQuery if not in cache
      gamelogs = await fetchPlayerGamelogsFromBigQuery(playerId)
      serverCache.set(cacheKey, gamelogs, PLAYER_GAMELOGS_TTL)
    }

    return NextResponse.json({
      data: gamelogs,
      playerId,
      cache: {
        status: serverCache.has(cacheKey) ? 'hit' : 'miss',
        timestamp: Date.now(),
        ttl: PLAYER_GAMELOGS_TTL,
      },
    })
  } catch (error) {
    console.error('Error fetching player gamelogs:', error)
    return NextResponse.json(
      { error: 'Failed to fetch player gamelogs data' },
      { status: 500 }
    )
  }
}